name: Latest YouTube Videos

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: # This allows you to run it manually right away

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Pull in YouTube videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YOUTUBE-CARDS"
          # Replace the placeholder below with your actual Channel ID
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=YOUR_CHANNEL_ID"
          max_post_count: 3 # Adjust this number to show more or fewer videos
